# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormGenerator.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtGui import QPixmap
from PyQt5 import QtGui
from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QPushButton,  QLabel, QTextEdit
from PyQt5.QtWidgets import QFileDialog,QDialog
from PyQt5.QtWidgets import QMainWindow
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5 import QtCore, QtGui, QtWidgets
import Lineimage
import random
class Ui_Form(QDialog):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(414, 520)
        Form.setFixedSize(414,520)
        Form.setStyleSheet("QWidget {\n"
"\n"
"    background-color: rgb(34,36,44);\n"
"\n"
"}")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(350, 450, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"\n"
"border:2px solid rgb(27,29,40);\n"
"border-radius:20px;\n"
"color: #939393;\n"
"padding-left:20px;\n"
"padding-right:20px;\n"
"    background-color: rgb(34,36,44);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"border:2px solid rgb(48,50,62);\n"
"\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"\n"
"border:2px solid rgb(85,170,255);\n"
"\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 450, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"\n"
"border:2px solid rgb(27,29,40);\n"
"border-radius:20px;\n"
"color: #939393;\n"
"padding-left:20px;\n"
"padding-right:20px;\n"
"    background-color: rgb(34,36,44);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"border:2px solid rgb(48,50,62);\n"
"\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"\n"
"border:2px solid rgb(85,170,255);\n"
"\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 450, 71, 41))
        self.label.setStyleSheet("QLabel {\n"
"\n"
"    image: url(:/Form/logo.png);\n"
"\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(20, 410, 381, 23))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"  background-color: #4994da;\n"
"  border: 1px solid #4994da;\n"
"  color: #F0F0F0;\n"
"  border-radius: 4px;\n"
"  text-align: center;\n"
"}\n"
"\n"
"QProgressBar:disabled {\n"
"  background-color: #19232D;\n"
"  border: 1px solid #32414B;\n"
"  color: #787878;\n"
"  border-radius: 4px;\n"
"  text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"  background-color: #37244c;\n"
"  color: #19232D;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QProgressBar::chunk:disabled {\n"
"  background-color: #14506E;\n"
"  color: #787878;\n"
"  border-radius: 4px;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 220, 371, 171))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 391, 191))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"\n"
"border:2px solid rgb(27,29,40);\n"
"border-radius:20px;\n"
"color: #939393;\n"
"padding-left:20px;\n"
"padding-right:20px;\n"
"    background-color: rgb(34,36,44);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"\n"
"border:2px solid rgb(48,50,62);\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"border:2px solid rgb(85,170,255);\n"
"\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "LineForm - Html Form Generator"))
        self.pushButton_8.setText(_translate("Form", "..."))
        self.pushButton_8.clicked.connect(self.profile)
        self.pushButton_3.setText(_translate("Form", "Fırlat :)"))
        self.pushButton_3.clicked.connect(self.generate)
    def profile(self):
        Browser = QFileDialog.getOpenFileName(self,'Images *.jpg *.png')
        Path = Browser[0]
        Mape = QPixmap(Path)
        boyut = Mape.scaled(271,161,QtCore.Qt.KeepAspectRatio)
        self.label_3.setPixmap(QPixmap(boyut))
        self.resize(Mape.width(),Mape.height())
    def generate(self):
        Formlistesi = ["""
            <div class="header"></div>
              <input type="checkbox" class="openSidebarMenu" id="openSidebarMenu">
              <label for="openSidebarMenu" class="sidebarIconToggle">
                <div class="spinner diagonal part-1"></div>
                <div class="spinner horizontal"></div>
                <div class="spinner diagonal part-2"></div>
              </label>
              <div id="sidebarMenu">
                <ul class="sidebarMenuInner">
                  <li>Jelena Jovanovic <span>Web Developer</span></li>
                  <li><a href="https://vanila.io" target="_blank">Company</a></li>
                  <li><a href="https://instagram.com/plavookac" target="_blank">Instagram</a></li>
                  <li><a href="https://twitter.com/plavookac" target="_blank">Twitter</a></li>
                  <li><a href="https://www.youtube.com/channel/UCDfZM0IK6RBgud8HYGFXAJg" target="_blank">YouTube</a></li>
                  <li><a href="https://www.linkedin.com/in/plavookac/" target="_blank">Linkedin</a></li>
                </ul>
              </div>
              <div id='center' class="main center">
                <div class="mainInner">
                  <div>PURE CSS SIDEBAR TOGGLE MENU</div>
                </div>
                <div class="mainInner">
                  <div>PURE CSS SIDEBAR TOGGLE MENU</div>
                </div>
                <div class="mainInner">
                  <div>PURE CSS SIDEBAR TOGGLE MENU</div>
                </div>
              </div>
          <style>
        
            @import url('https://fonts.googleapis.com/css?family=Varela+Round');
        html, body {
            overflow-x: hidden;
            height: 100%;
        }
        body {
            background: #fff;
            padding: 0;
            margin: 0;
            font-family: 'Varela Round', sans-serif;
        }
        .header {
            display: block;
            margin: 0 auto;
            width: 100%;
            max-width: 100%;
            box-shadow: none;
            background-color: #FC466B;
            position: fixed;
            height: 60px!important;
            overflow: hidden;
            z-index: 10;
        }
        .main {
            margin: 0 auto;
            display: block;
            height: 100%;
            margin-top: 60px;
        }
        .mainInner{
            display: table;
            height: 100%;
            width: 100%;
            text-align: center;
        }
        .mainInner div{
            display:table-cell;
            vertical-align: middle;
            font-size: 3em;
            font-weight: bold;
            letter-spacing: 1.25px;
        }
        #sidebarMenu {
            height: 100%;
            position: fixed;
            left: 0;
            width: 250px;
            margin-top: 60px;
            transform: translateX(-250px);
            transition: transform 250ms ease-in-out;
            background: linear-gradient(180deg, #FC466B 0%, #3F5EFB 100%);
        }
        .sidebarMenuInner{
            margin:0;
            padding:0;
            border-top: 1px solid rgba(255, 255, 255, 0.10);
        }
        .sidebarMenuInner li{
            list-style: none;
            color: #fff;
            text-transform: uppercase;
            font-weight: bold;
            padding: 20px;
            cursor: pointer;
            border-bottom: 1px solid rgba(255, 255, 255, 0.10);
        }
        .sidebarMenuInner li span{
            display: block;
            font-size: 14px;
            color: rgba(255, 255, 255, 0.50);
        }
        .sidebarMenuInner li a{
            color: #fff;
            text-transform: uppercase;
            font-weight: bold;
            cursor: pointer;
            text-decoration: none;
        }
        input[type="checkbox"]:checked ~ #sidebarMenu {
            transform: translateX(0);
        }
        
        input[type=checkbox] {
            transition: all 0.3s;
            box-sizing: border-box;
            display: none;
        }
        .sidebarIconToggle {
            transition: all 0.3s;
            box-sizing: border-box;
            cursor: pointer;
            position: absolute;
            z-index: 99;
            height: 100%;
            width: 100%;
            top: 22px;
            left: 15px;
            height: 22px;
            width: 22px;
        }
        .spinner {
            transition: all 0.3s;
            box-sizing: border-box;
            position: absolute;
            height: 3px;
            width: 100%;
            background-color: #fff;
        }
        .horizontal {
            transition: all 0.3s;
            box-sizing: border-box;
            position: relative;
            float: left;
            margin-top: 3px;
        }
        .diagonal.part-1 {
            position: relative;
            transition: all 0.3s;
            box-sizing: border-box;
            float: left;
        }
        .diagonal.part-2 {
            transition: all 0.3s;
            box-sizing: border-box;
            position: relative;
            float: left;
            margin-top: 3px;
        }
        input[type=checkbox]:checked ~ .sidebarIconToggle > .horizontal {
            transition: all 0.3s;
            box-sizing: border-box;
            opacity: 0;
        }
        input[type=checkbox]:checked ~ .sidebarIconToggle > .diagonal.part-1 {
            transition: all 0.3s;
            box-sizing: border-box;
            transform: rotate(135deg);
            margin-top: 8px;
        }
        input[type=checkbox]:checked ~ .sidebarIconToggle > .diagonal.part-2 {
            transition: all 0.3s;
            box-sizing: border-box;
            transform: rotate(-135deg);
            margin-top: -9px;
        }
            
      </style>
        """,
        """
      <html>
      <head>  
      </head>
      <body><div class="area"></div><nav class="main-menu">
                <ul>
                    <li>
                        <a href="http://justinfarrow.com">
                            <i class="fa fa-home fa-2x"></i>
                            <span class="nav-text">
                                Dashboard
                            </span>
                        </a>
                      
                    </li>
                    <li class="has-subnav">
                        <a href="#">
                            <i class="fa fa-laptop fa-2x"></i>
                            <span class="nav-text">
                                Stars Components
                            </span>
                        </a>
                        
                    </li>
                    <li class="has-subnav">
                        <a href="#">
                           <i class="fa fa-list fa-2x"></i>
                            <span class="nav-text">
                                Forms
                            </span>
                        </a>
                        
                    </li>
                    <li class="has-subnav">
                        <a href="#">
                           <i class="fa fa-folder-open fa-2x"></i>
                            <span class="nav-text">
                                Pages
                            </span>
                        </a>
                       
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-bar-chart-o fa-2x"></i>
                            <span class="nav-text">
                                Graphs and Statistics
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-font fa-2x"></i>
                            <span class="nav-text">
                               Quotes
                            </span>
                        </a>
                    </li>
                    <li>
                       <a href="#">
                           <i class="fa fa-table fa-2x"></i>
                            <span class="nav-text">
                                Tables
                            </span>
                        </a>
                    </li>
                    <li>
                       <a href="#">
                            <i class="fa fa-map-marker fa-2x"></i>
                            <span class="nav-text">
                                Maps
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                           <i class="fa fa-info fa-2x"></i>
                            <span class="nav-text">
                                Documentation
                            </span>
                        </a>
                    </li>
                </ul>
    
                <ul class="logout">
                    <li>
                       <a href="#">
                             <i class="fa fa-power-off fa-2x"></i>
                            <span class="nav-text">
                                Logout
                            </span>
                        </a>
                    </li>  
                </ul>
            </nav>
      </body>
        </html>
                
        <style>
        
           @import url(//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css);
            }
            @import url(https://fonts.googleapis.com/css?family=Titillium+Web:300);
            .fa-2x {
            font-size: 2em;
            }
            .fa {
            position: relative;
            display: table-cell;
            width: 60px;
            height: 36px;
            text-align: center;
            vertical-align: middle;
            font-size:20px;
            }
            
            
            .main-menu:hover,nav.main-menu.expanded {
            width:250px;
            overflow:visible;
            }
            
            .main-menu {
            background:#212121;
            border-right:1px solid #e5e5e5;
            position:absolute;
            top:0;
            bottom:0;
            height:100%;
            left:0;
            width:60px;
            overflow:hidden;
            -webkit-transition:width .05s linear;
            transition:width .05s linear;
            -webkit-transform:translateZ(0) scale(1,1);
            z-index:1000;
            }
            
            .main-menu>ul {
            margin:7px 0;
            }
            
            .main-menu li {
            position:relative;
            display:block;
            width:250px;
            }
            
            .main-menu li>a {
            position:relative;
            display:table;
            border-collapse:collapse;
            border-spacing:0;
            color:#999;
             font-family: arial;
            font-size: 14px;
            text-decoration:none;
            -webkit-transform:translateZ(0) scale(1,1);
            -webkit-transition:all .1s linear;
            transition:all .1s linear;
              
            }
            
            .main-menu .nav-icon {
            position:relative;
            display:table-cell;
            width:60px;
            height:36px;
            text-align:center;
            vertical-align:middle;
            font-size:18px;
            }
            
            .main-menu .nav-text {
            position:relative;
            display:table-cell;
            vertical-align:middle;
            width:190px;
              font-family: 'Titillium Web', sans-serif;
            }
            
            .main-menu>ul.logout {
            position:absolute;
            left:0;
            bottom:0;
            }
            
            .no-touch .scrollable.hover {
            overflow-y:hidden;
            }
            
            .no-touch .scrollable.hover:hover {
            overflow-y:auto;
            overflow:visible;
            }
            
            a:hover,a:focus {
            text-decoration:none;
            }
            
            nav {
            -webkit-user-select:none;
            -moz-user-select:none;
            -ms-user-select:none;
            -o-user-select:none;
            user-select:none;
            }
            
            nav ul,nav li {
            outline:0;
            margin:0;
            padding:0;
            }
            .main-menu li:hover>a,nav.main-menu li.active>a,.dropdown-menu>li>a:hover,.dropdown-menu>li>a:focus,.dropdown-menu>.active>a,.dropdown-menu>.active>a:hover,.dropdown-menu>.active>a:focus,.no-touch .dashboard-page nav.dashboard-menu ul li:hover a,.dashboard-page nav.dashboard-menu ul li.active a {
            color:#fff;
            background-color:#5fa2db;
            }
            .area {
            float: left;
            background: #e2e2e2;
            width: 100%;
            height: 100%;
            }
            @font-face {
              font-family: 'Titillium Web';
              font-style: normal;
              font-weight: 300;
              src: local('Titillium WebLight'), local('TitilliumWeb-Light'), url(http://themes.googleusercontent.com/static/fonts/titilliumweb/v2/anMUvcNT0H1YN4FII8wpr24bNCNEoFTpS2BTjF6FB5E.woff) format('woff');
            }      
        </style>
        ""","""
        <div id="viewport">
          <!-- Sidebar -->
          <div id="sidebar">
            <header>
              <a href="#">My App</a>
            </header>
            <ul class="nav">
              <li>
                <a href="#">
                  <i class="zmdi zmdi-view-dashboard"></i> Dashboard
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="zmdi zmdi-link"></i> Shortcuts
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="zmdi zmdi-widgets"></i> Overview
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="zmdi zmdi-calendar"></i> Events
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="zmdi zmdi-info-outline"></i> About
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="zmdi zmdi-settings"></i> Services
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="zmdi zmdi-comment-more"></i> Contact
                </a>
              </li>
            </ul>
          </div>
          <!-- Content -->
          <div id="content">
            <nav class="navbar navbar-default">
              <div class="container-fluid">
                <ul class="nav navbar-nav navbar-right">
                  <li>
                    <a href="#"><i class="zmdi zmdi-notifications text-danger"></i>
                    </a>
                  </li>
                  <li><a href="#">Test User</a></li>
                </ul>
              </div>
            </nav>
            <div class="container-fluid">
              <h1>Simple Sidebar</h1>
              <p>
                Make sure to keep all page content within the 
                <code>#content</code>.
              </p>
            </div>
          </div>
        </div>  
        <style>
        
        @import url('https://fonts.googleapis.com/css?family=Roboto:300,400,400i,500');
        body {
          overflow-x: hidden;
          font-family: 'Roboto', sans-serif;
          font-size: 16px;
        }
        
        /* Toggle Styles */
        
        #viewport {
          padding-left: 250px;
          -webkit-transition: all 0.5s ease;
          -moz-transition: all 0.5s ease;
          -o-transition: all 0.5s ease;
          transition: all 0.5s ease;
        }
        
        #content {
          width: 100%;
          position: relative;
          margin-right: 0;
        }
        
        /* Sidebar Styles */
        
        #sidebar {
          z-index: 1000;
          position: fixed;
          left: 250px;
          width: 250px;
          height: 100%;
          margin-left: -250px;
          overflow-y: auto;
          background: #37474F;
          -webkit-transition: all 0.5s ease;
          -moz-transition: all 0.5s ease;
          -o-transition: all 0.5s ease;
          transition: all 0.5s ease;
        }
        
        #sidebar header {
          background-color: #263238;
          font-size: 20px;
          line-height: 52px;
          text-align: center;
        }
        
        #sidebar header a {
          color: #fff;
          display: block;
          text-decoration: none;
        }
        
        #sidebar header a:hover {
          color: #fff;
        }
        
        #sidebar .nav{
          
        }
        
        #sidebar .nav a{
          background: none;
          border-bottom: 1px solid #455A64;
          color: #CFD8DC;
          font-size: 14px;
          padding: 16px 24px;
        }
        
        #sidebar .nav a:hover{
          background: none;
          color: #ECEFF1;
        }
        
        #sidebar .nav a i{
          margin-right: 16px;
        }
        
        </style>
        ""","""
        <div class="sidebar-container">
          <div class="sidebar-logo">
            Project Name
          </div>
          <ul class="sidebar-navigation">
            <li class="header">Navigation</li>
            <li>
              <a href="#">
                <i class="fa fa-home" aria-hidden="true"></i> Homepage
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fa fa-tachometer" aria-hidden="true"></i> Dashboard
              </a>
            </li>
            <li class="header">Another Menu</li>
            <li>
              <a href="#">
                <i class="fa fa-users" aria-hidden="true"></i> Friends
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fa fa-cog" aria-hidden="true"></i> Settings
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fa fa-info-circle" aria-hidden="true"></i> Information
              </a>
            </li>
          </ul>
        </div>
        
        <div class="content-container">
        
          <div class="container-fluid">
        
            <!-- Main component for a primary marketing message or call to action -->
            <div class="jumbotron">
              <h1>Navbar example</h1>
              <p>This example is a quick exercise to illustrate how the default, static and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
              <p>To see the difference between static and fixed top navbars, just scroll.</p>
              <p>
                <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>
              </p>
            </div>
        
          </div>
        </div>
        <style>
                
        .sidebar-container {
          position: fixed;
          width: 220px;
          height: 100%;
          left: 0;
          overflow-x: hidden;
          overflow-y: auto;
          background: #1a1a1a;
          color: #fff;
        }
        
        .content-container {
          padding-top: 20px;
        }
        
        .sidebar-logo {
          padding: 10px 15px 10px 30px;
          font-size: 20px;
          background-color: #2574A9;
        }
        
        .sidebar-navigation {
          padding: 0;
          margin: 0;
          list-style-type: none;
          position: relative;
        }
        
        .sidebar-navigation li {
          background-color: transparent;
          position: relative;
          display: inline-block;
          width: 100%;
          line-height: 20px;
        }
        
        .sidebar-navigation li a {
          padding: 10px 15px 10px 30px;
          display: block;
          color: #fff;
        }
        
        .sidebar-navigation li .fa {
          margin-right: 10px;
        }
        
        .sidebar-navigation li a:active,
        .sidebar-navigation li a:hover,
        .sidebar-navigation li a:focus {
          text-decoration: none;
          outline: none;
        }
        
        .sidebar-navigation li::before {
          background-color: #2574A9;
          position: absolute;
          content: '';
          height: 100%;
          left: 0;
          top: 0;
          -webkit-transition: width 0.2s ease-in;
          transition: width 0.2s ease-in;
          width: 3px;
          z-index: -1;
        }
        
        .sidebar-navigation li:hover::before {
          width: 100%;
        }
        
        .sidebar-navigation .header {
          font-size: 12px;
          text-transform: uppercase;
          background-color: #151515;
          padding: 10px 15px 10px 30px;
        }
        
        .sidebar-navigation .header::before {
          background-color: transparent;
        }
        
        .content-container {
          padding-left: 220px;
        }
                
        </style>
        ""","""
            
        <link href='https://fonts.googleapis.com/css?family=Lato:400,500,900' rel='stylesheet' type='text/css'>  
        <div id="wrapper">     
        
        <div id="sidebar-menu">
            <div id="toggleMenu">
                <div class="list"></div>
                <div class="thumbs"></div>    
            </div> 
            <ul>
                <li class="DASHBOARD"><span>DASHBOARD</span></li>
                <li class="USERS"><span>USERS</span></li>
                <li class="PRIORITY"><span>PRIORITY</span></li>
                <li class="COLLECTIONS"><span>COLLECTIONS</span></li>
                <li class="ARCHIVED"><span>ARCHIVED</span></li>
                <li class="DELETED"><span>DELETED</span></li>
                <li class="TRENDS"><span>TRENDS</span></li>
                <li class="TASKS"><span>TASKS</span></li>
                <li class="FILTERS"><span>FILTERS</span></li>
                <li class="STATS"><span>STATS</span></li>
                <li class="SETTINGS"><span>SETTINGS</span></li>        
            </ul>
            
            
        </div>
        
        <div id="dropdown">
            <div id="drop-select">Select a branch</div>
            <div id="dropdown-list">
                <div class="header">Group header</div>
                <ul>
                    <li>Filmore District</li>
                    <li>Mission District</li>
                    <li>Northshare Beach</li>
                    <li>Some other branch</li>
                </ul>
            </div>
        </div>
        
        
        <div class="sortable-accordion">
             <h3>GROUP 1</h3>
        
            <div class="inner">
                 <ul class="sortable">
                    <li class="ui-state-default">Item 1</li>  
                    <li class="ui-state-default">Item 2</li>  
                    <li class="ui-state-default">Item 3</li>  
                    <li class="ui-state-default">Item 4</li>  
                </ul> 
            </div>
             <h3>GROUP 2</h3>
        
            <div class="inner">
                <ul class="sortable">
                   <li class="ui-state-default">Item 1</li>  
                   <li class="ui-state-default">Item 2</li>          
                </ul> 
            </div>
             <h3>GROUP 3</h3>
        
            <div class="inner">
                <ul class="sortable">
                    <li class="ui-state-default">Item 1</li>  
                    <li class="ui-state-default">Item 2</li>  
                    <li class="ui-state-default">Item 3</li>  
                    <li class="ui-state-default">Item 4</li>  
                </ul> 
            </div>
        </div>
        <div id="submenu">
                <a class="compare" href=""></a>
            <a class="revisions" href=""></a>
            <a class="edit" href=""></a>
            <span></span>
        </div>
            
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/jquery-ui.min.js"></script>
        <style>
        
                    /*	Reset & General
            ---------------------------------------------------------------------- */
            * { margin: 0px; padding: 0px; }
            body {
                background: #ebeef0;
                font:12px "Lato", sans-serif; 
            }
            #wrapper{
              width: 666px;
              margin: 0 auto;
              position: relative;
            }
            #sidebar-menu{
                background:#229bdc;
                overflow:hidden;
                border-radius:5px;
                position:absolute;
                top: 60px;
                left: 0;
                height:62 0px;
                width:55px;
                color:#abe2ff;
                font-size:12px;
                font-weight:900;
                -webkit-transition: all 200ms ease-out;
                       -moz-transition: all 300ms cubic-bezier(0.000, 0.995, 0.990, 1.000);
                        -ms-transition: all 300ms cubic-bezier(0.000, 0.995, 0.990, 1.000);
                         -o-transition: all 300ms cubic-bezier(0.000, 0.995, 0.990, 1.000);
                            transition: all 300ms cubic-bezier(0.000, 0.995, 0.990, 1.000);
            }
            #sidebar-menu.animate{
                width:210px;
                -webkit-transition: all 200ms ease-out;
                       -moz-transition: all 300ms cubic-bezier(0.000, 0.995, 0.990, 1.000);
                        -ms-transition: all 300ms cubic-bezier(0.000, 0.995, 0.990, 1.000);
                         -o-transition: all 300ms cubic-bezier(0.000, 0.995, 0.990, 1.000);
                            transition: all 300ms cubic-bezier(0.000, 0.995, 0.990, 1.000);	
            }
            
            #toggleMenu{
                background:#1888c4;
                height:37px;
            }
            #toggleMenu .list{
                position:absolute;
                top: 12px;
                cursor:pointer;
                right: 8px;;
                height:30px;
                width:30px;
                height:30px;
                background:url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/toggle-list.png") 0 0 no-repeat	
            }
            #toggleMenu .thumbs{
                position:absolute;
                display:none;	
                top: 9px;
                cursor:pointer;
                right: 3px;
                height:30px;
                width:30px;
                height:30px;
                background:url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/toggle-thumbs.png") 0 0 no-repeat;
            }
            
            #sidebar-menu li{
                background:url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/sidemenu-sprite.png") 0 0 no-repeat;
                padding: 15px 0 15px 54px;
                margin: 1px 4px 1px 4px;
                list-style: none;
            }
            
            #sidebar-menu ul{margin-top:11px;}
            #sidebar-menu li.DASHBOARD{background-position: 7px 14px;}
            #sidebar-menu li.DASHBOARD:hover{background-position: -324px 14px; color:#fff;cursor:pointer;}
            #sidebar-menu li.selected.DASHBOARD{background-position: -620px 14px; color:#1888c4;cursor:pointer;}
            
            #sidebar-menu li.USERS{background-position: 9px -33px; }
            #sidebar-menu li.USERS:hover{background-position:  -322px -33px;color:#fff;cursor:pointer;}
            #sidebar-menu li.selected.USERS{background-position:  -618px -33px;color:#1888c4;cursor:pointer;}
            
            #sidebar-menu li.PRIORITY{background-position: 9px -80px;}
            #sidebar-menu li.PRIORITY:hover{background-position: -322px -80px;color:#fff;cursor:pointer;}
            #sidebar-menu li.selected.PRIORITY{background-position: -618px -80px;color:#1888c4;cursor:pointer;}
            
            #sidebar-menu li.COLLECTIONS{background-position: 8px -127px;}
            #sidebar-menu li.COLLECTIONS:hover{background-position: -323px -127px;color:#fff;cursor:pointer;}
            #sidebar-menu li.selected.COLLECTIONS{background-position: -619px -127px;color:#1888c4;cursor:pointer;}
            
            #sidebar-menu li.ARCHIVED{background-position: 8px -175px;}
            #sidebar-menu li.ARCHIVED:hover{background-position: -323px -175px;color:#fff;cursor:pointer;}
            #sidebar-menu li.selected.ARCHIVED{background-position: -619px -175px;color:#1888c4;cursor:pointer;}
            
            #sidebar-menu li.DELETED{background-position: 8px -223px;}
            #sidebar-menu li.DELETED:hover{background-position: -323px -223px;color:#fff;cursor:pointer;}
            #sidebar-menu li.selected.DELETED{background-position: -619px -223px;color:#1888c4;cursor:pointer;}
            
            #sidebar-menu li.TRENDS{background-position: 8px -270px;}
            #sidebar-menu li.TRENDS:hover{background-position: -323px -270px;color:#fff;cursor:pointer;}
            #sidebar-menu li.selected.TRENDS{background-position: -619px -270px;color:#1888c4;cursor:pointer;}
            
            #sidebar-menu li.TASKS{background-position: 7px -319px;}
            #sidebar-menu li.TASKS:hover{background-position: -324px -319px;color:#fff;cursor:pointer;}
            #sidebar-menu li.selected.TASKS{background-position: -620px -319px;color:#1888c4;cursor:pointer;}
            
            #sidebar-menu li.FILTERS{background-position: 7px -365px;}
            #sidebar-menu li.FILTERS:hover{background-position: -324px -365px;color:#fff;cursor:pointer;}
            #sidebar-menu li.selected.FILTERS{background-position: -620px -365px;color:#1888c4;cursor:pointer;}
            
            #sidebar-menu li.STATS{background-position: 7px -413px;}
            #sidebar-menu li.STATS:hover{background-position: -324px -413px;color:#fff;cursor:pointer;}
            #sidebar-menu li.selected.STATS{background-position: -620px -413px;color:#1888c4;cursor:pointer;}
            
            #sidebar-menu li.SETTINGS{  background-position: 7px -507px;  margin-top: 75px;  margin-bottom: 4px;}
            #sidebar-menu li.SETTINGS:hover{background-position: -324px -507px;color:#fff;cursor:pointer;}
            #sidebar-menu li.selected.SETTINGS{background-position: -620px -507px;color:#1888c4;cursor:pointer;}
            
            #sidebar-menu li{padding-left: 4px ;height: 15px;}
            #sidebar-menu.animate li{padding-left:54px  ;}
            #sidebar-menu li span{opacity:0;margin-left:10px;}
            #sidebar-menu li.selected{background-color:#fff; color:#1888c4; border-radius:4px;}
            #sidebar-menu li.selected:hover{color:#1888c4}
            
            .sortable-accordion {
                margin:20px;
                border-radius:5px;
                background:#1888c4;
                overflow:hidden;
                width:200px;
                position:absolute;
                top: 365px;
              left: 371px;
            }
            .sortable-accordion h3 {
                color:#fff;
                cursor:pointer;
                margin:0;
                padding:13px 16px 13px 18px;
                background:#229bdc;
                font-size:12px;
                text-transform:uppercase;
            }
            .sortable-accordion h3:hover{
                background:#1f96d6;
            }
            .sortable-accordion h3.current {
                cursor:default
            }
            .sortable-accordion li{
                font-size:14px;
                color:#abe2ff;
                font-weight:400;
                 padding: 11px 10px 11px 43px;
              background: url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/sort.png") 17px 13px no-repeat;
              list-style:none;
              position:relative;
            }
            .sortable-accordion li:hover{
                cursor:pointer;	
                background-color:#1784bf;
            }
            .ui-sortable-helper{
                cursor:move; opacity:0.8; background-color:#157eb6;
                box-shadow:0px 5px 10px -5px rgba(0, 0, 0, 0.3);	
            }
            .ui-sortable-placeholder{
                border: 2px dotted #0e9ce8 !important;
                background:#158bca !important;
                padding:11px 10px 11px 43px;
                height:15px;
            }
            .options{
                background:url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/options.png") 0 0 no-repeat;
                width:26px;
                height:21px;
                display:block;
                position:absolute;
                top:10px;
                right:10px;
            }
            #submenu{
                background-color:#157eb6;
                position:absolute;
                top:0px;
                left:200px;
              width: 100px;
                border-radius:4px;
                box-shadow:0px 5px 10px -5px rgba(0, 0, 0, 0.3);
                padding:2px 5px 2px 1px;
                display:none;
            }
            #submenu span{
                width: 15px;
                height: 15px;
                display:block;
                background-color:#157eb6;
                position:absolute;
                left: -3px;
                top: 12px;
                -ms-transform: rotate(45deg); 
                -webkit-transform: rotate(45deg); 
                transform: rotate(45deg);	
                 z-index:1;
            }
            #submenu a{
              float: left;
              width: 27px;
              height: 20px;
              padding: 8px 3px 8px;
              background:url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/submenu-sprite.png") 8px 9px no-repeat;	
              position:relative;
              z-index:2;
            }
            #submenu a.compare:hover{background-position:8px -22px}
            #submenu a.revisions{background-position:-27px 9px}
            #submenu a.revisions:hover{background-position:-27px -22px}
            #submenu a.edit{background-position:-64px 9px}
            #submenu a.edit:hover{background-position:-64px -22px}
            
            
            #dropdown{	
                position:absolute;
                top: 60px;
                left: 316px;
            }
            #drop-select{
                border-radius:4px;
                background:#229bdc url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/dropdown-arrows.png") 313px 18px no-repeat;
                text-transform:uppercase;
                color:#fff;
                width:300px;
                padding:17px 20px;
                font-weight:700;
                font-size: 13px;	
                cursor:pointer;
            }
            #dropdown-list{	
                border-radius:4px;
                background:#229bdc;	
                padding-bottom:1px;
                width:400px;
                margin-left:0px;	
                margin-top:10px;
                opacity:0;
                -webkit-transition: all 200ms ease-out;
                       -moz-transition: all 300ms cubic-bezier(0.000, 0.995, 0.990, 1.000);
                        -ms-transition: all 300ms cubic-bezier(0.000, 0.995, 0.990, 1.000);
                         -o-transition: all 300ms cubic-bezier(0.000, 0.995, 0.990, 1.000);
                            transition: all 300ms cubic-bezier(0.000, 0.995, 0.990, 1.000);	
            }
            #dropdown-list.animate{
            margin-top:-3px;
                opacity:1;
                -webkit-transition: all 200ms ease-out;
                       -moz-transition: all 300ms cubic-bezier(0.000, 0.995, 0.990, 1.000);
                        -ms-transition: all 300ms cubic-bezier(0.000, 0.995, 0.990, 1.000);
                         -o-transition: all 300ms cubic-bezier(0.000, 0.995, 0.990, 1.000);
                            transition: all 300ms cubic-bezier(0.000, 0.995, 0.990, 1.000);	
            }
            #dropdown-list .header{
                background:#1888c4; color:#fff;
                padding:12px 20px;
                text-transform:uppercase;
                font-weight:700;
                border-radius:0 5px 0 0;
            }
            #dropdown-list li{
                list-style:none;
                padding:12px 20px;
                color:#abe2ff;
                font-size:15px;
                font-weight:500;
                margin:10px 4px;
                background:url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/bullet.png") 374px 17px no-repeat;
            }
            #dropdown-list li:hover{
                background-color:#fff;
                border-radius:4px; 
                cursor:pointer;
                color:#1888c4;
            }           
        </style>
        <script>
        
        $(document).ready(function(){	
        
            $(function () {
            //  Accordion Panels
            $(".sortable-accordion div").show();
            $('.sortable-accordion div').slideToggle('slow');
            $(".sortable-accordion h3").click(function () {
                $(this).next(".inner").slideToggle().siblings(".inner:visible").slideUp();
                $(this).toggleClass("current");
                $(this).siblings("h3").removeClass("current");
            });
        });
          
        $( ".sortable" ).sortable({   
            placeholder: "ui-sortable-placeholder"   
        }).find("li").append("<span class='options'></span>");  
        
        $('#submenu a').click(function(){return false;})
        
        $('.options').click(function(){
            var childpos = $(this).offset();  
          var  parentpos = $(this).parent().offset();
          
          var posLeft = childpos.left - parentpos.left;
        
            $('#submenu').css({'top':(childpos.top - 10)+"px", 'left': (posLeft+420)+"px"}).fadeIn(200);
            $('#submenu').mouseleave(function(){$(this).fadeOut(200);});
        });
        
        $('#toggleMenu .list').click(function(){
            $('#sidebar-menu li span').animate({'opacity':1, 'margin-left':'0px'});
            $('#sidebar-menu').toggleClass('animate');
            $('#toggleMenu .list').fadeOut();
            $('#toggleMenu .thumbs').fadeIn();
        
        });
        
        $('#toggleMenu .thumbs').click(function(){
            $('#sidebar-menu li span').css({'opacity': 0, 'margin-left': "10px"});
            $('#sidebar-menu').toggleClass('animate');	
            $('#toggleMenu .thumbs').fadeOut();
            $('#toggleMenu .list').fadeIn();	
            
        });
        
        $("#sidebar-menu li").click(function(){
            $("#sidebar-menu li").not(this).removeClass("selected");
            $(this).toggleClass("selected");
        });
        
        $('#drop-select').click(function(){
            $('#dropdown-list').toggleClass('animate');
        });
        
        $('#dropdown-list li').click(function(){$('#dropdown-list').removeClass('animate');});
        
        });     
        </script>
        """]
        self.lineEdit.setText(f"""{random.choice(Formlistesi)}""")
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
